#!/usr/bin/env bash
# docker wrapper for building all projects just like they are built in ci
set -euo pipefail
SCRIPT_PATH="$(cd "$(dirname "$0")"; pwd -P)"
(
  cd ${SCRIPT_PATH}
  (cd ci-build && docker build -t ci-build .)
  while read project; do
    echo "Building ${project}..."
    docker run \
      -v ${PWD}/..:/code \
      --rm ci-build /bin/bash -c "cd /code/projects/${project} && make"
  done < <(find -mindepth 1 -maxdepth 2 -name Makefile -exec dirname {} \;)
)
