name: inception

on:
  push:

env:
  PROJECT_ROOT: projects
  BASE_BRANCH: main
  BEFORE_SHA: ${{ github.event.before }}
  
jobs:
  inception:
    runs-on: ubuntu-24.04
    outputs:
      projects: ${{ steps.detect.outputs.projects }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Inception
      id: detect
      run: |
        results=$(bin/inception 2>/dev/stderr)
        echo "projects=$(echo "$results" | jq -rc 'map(.name)')" >> $GITHUB_OUTPUT

  run:
    needs: inception
    if: ${{ needs.inception.outputs.projects != '[]' }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        project: ${{ fromJson(needs.inception.outputs.projects) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ./.github/actions/build
      with:
        PROJECT: ${{ matrix.project }}
        PROJECT_ROOT: ${{ env.PROJECT_ROOT }}/${{ matrix.project}}
      

